### ISSUE TITLE
Add images to the application

### ISSUE THREAD

**Issue by adamgmcfadden** [adamgmcfadden/aws-thought#4]
As a user, I want to add an image to my thought

As a user, I want to see all images

As a user, I want to view images of a user

**Comment by exist08** [comment]
I can work on this

**Comment by exist08** [comment]
kindly assign it to me

**Comment by adamgmcfadden** [comment]
hello, thank you for showing interest but I'm simply taking a course that has me building this app and they had me fill in these issues to "set up the build progression". I do not intend to share the work with anyone as this is an opportunity for me to learn. thanks again
